/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as EmotionRouteImport } from './routes/emotion'
import { Route as GroundRouteImport } from './routes/ground'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProvingRouteImport } from './routes/proving'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as VoiceRouteImport } from './routes/voice'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionRoute = EmotionRouteImport.update({
  id: '/emotion',
  path: '/emotion',
  getParentRoute: () => rootRouteImport,
} as any)
const GroundRoute = GroundRouteImport.update({
  id: '/ground',
  path: '/ground',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvingRoute = ProvingRouteImport.update({
  id: '/proving',
  path: '/proving',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/emotion': typeof EmotionRoute
  '/ground': typeof GroundRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/proving': typeof ProvingRoute
  '/resources': typeof ResourcesRoute
  '/training': typeof TrainingRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/emotion': typeof EmotionRoute
  '/ground': typeof GroundRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/proving': typeof ProvingRoute
  '/resources': typeof ResourcesRoute
  '/training': typeof TrainingRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/emotion': typeof EmotionRoute
  '/ground': typeof GroundRoute
  '/music': typeof MusicRoute
  '/profile': typeof ProfileRoute
  '/proving': typeof ProvingRoute
  '/resources': typeof ResourcesRoute
  '/training': typeof TrainingRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/emotion'
    | '/ground'
    | '/music'
    | '/profile'
    | '/proving'
    | '/resources'
    | '/training'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/emotion'
    | '/ground'
    | '/music'
    | '/profile'
    | '/proving'
    | '/resources'
    | '/training'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/emotion'
    | '/ground'
    | '/music'
    | '/profile'
    | '/proving'
    | '/resources'
    | '/training'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  EmotionRoute: typeof EmotionRoute
  GroundRoute: typeof GroundRoute
  MusicRoute: typeof MusicRoute
  ProfileRoute: typeof ProfileRoute
  ProvingRoute: typeof ProvingRoute
  ResourcesRoute: typeof ResourcesRoute
  TrainingRoute: typeof TrainingRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotion': {
      id: '/emotion'
      path: '/emotion'
      fullPath: '/emotion'
      preLoaderRoute: typeof EmotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ground': {
      id: '/ground'
      path: '/ground'
      fullPath: '/ground'
      preLoaderRoute: typeof GroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proving': {
      id: '/proving'
      path: '/proving'
      fullPath: '/proving'
      preLoaderRoute: typeof ProvingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  EmotionRoute: EmotionRoute,
  GroundRoute: GroundRoute,
  MusicRoute: MusicRoute,
  ProfileRoute: ProfileRoute,
  ProvingRoute: ProvingRoute,
  ResourcesRoute: ResourcesRoute,
  TrainingRoute: TrainingRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
